[target]
base_url = "https://api.example.com"

[scenarios]
[scenarios.health_check]
method = "GET"
path = "/api/health"
weight = 5
headers = {"User-Agent" = "Klavier/1.0"}

[scenarios.login]
method = "GET"
path = "/api/auth/login"
weight = 1
headers = {"User-Agent" = "Klavier/1.0"}

[timings]
base_request_interval_ms = 1000
test_duration_seconds = 60

