[target]
base_url = "https://api.example.com"

[scenarios]
[scenarios.health_check]
weight = 5
[[scenarios.health_check.requests]]
method = "GET"
path = "/api/health"
headers = {"User-Agent" = "Klavier/1.0"}

[scenarios.login]
weight = 1
[[scenarios.login.requests]]
method = "GET"
path = "/api/auth/login"
headers = {"User-Agent" = "Klavier/1.0"}

[timings]
base_request_interval_ms = 1000
test_duration_seconds = 60

